[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "oneprompt-sdk"
version = "0.1.2"
description = "Lightweight oneprompt cloud SDK."
readme = "README.md"
license = {text = "PolyForm Shield License 1.0.0"}
requires-python = ">=3.12"
authors = [
    { name = "oneprompt"},
]
keywords = ["ai", "sdk", "cloud", "data-analysis", "llm"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "httpx>=0.27.2",
    "python-dotenv>=1.0",
]

[project.urls]
Homepage = "https://github.com/oneprompteu/oneprompt"
Documentation = "https://github.com/oneprompteu/oneprompt#readme"
Repository = "https://github.com/oneprompteu/oneprompt"
Issues = "https://github.com/oneprompteu/oneprompt/issues"

[tool.hatch.build.targets.wheel]
packages = ["oneprompt_sdk"]

[tool.hatch.build.targets.sdist]
include = [
    "oneprompt_sdk/**/*.py",
    "README.md",
    "pyproject.toml",
]
